l1={1: "Sapiens: A Brief History of Humankind",
2: "Homo Deus",
3: "21 Lessons for the 21st Century",
4: "A Brief History of Time",
5: "The Theory of Everything",
6: "Cosmos",
7: "The Selfish Gene",
8: "The Gene: An Intimate History",
9: "Thinking, Fast and Slow",
10: "Blink",
11: "Outliers",
12: "Freakonomics",
13: "Super Freakonomics",
14: "The Wealth of Nations",
15: "Capital in the Twenty-First Century",
16: "Rich Dad Poor Dad",
17: "The Intelligent Investor",
18: "Security Analysis",
19: "Principles: Life and Work",
20: "Atomic Habits",
21: "The Power of Habit",
22: "Deep Work",
23: "The 7 Habits of Highly Effective People",
24: "Man’s Search for Meaning",
25: "Meditations",
26: "Beyond Good and Evil",
27: "Thus Spoke Zarathustra",
28: "The Republic",
29: "Nicomachean Ethics",
30: "Critique of Pure Reason",
31: "The Art of War",
32: "The Prince",
33: "On War",
34: "The Laws of Human Nature",
35: "12 Rules for Life",
36: "Guns, Germs, and Steel",
37: "The Silk Roads",
38: "A People’s History of the United States",
39: "The Lessons of History",
40: "The Diary of a Young Girl",
41: "Long Walk to Freedom",
42: "The Story of My Experiments with Truth",
43: "Wings of Fire",
44: "Ignited Minds",
45: "India After Gandhi",
46: "Discovery of India",
47: "The Alchemist",
48: "To Kill a Mockingbird",
49: "1984",
50: "Brave New World",
51: "Animal Farm",
52: "The Great Gatsby",
53: "Pride and Prejudice",
54: "Jane Eyre",
55: "Wuthering Heights",
56: "Moby Dick",
57: "War and Peace",
58: "Crime and Punishment",
59: "The Brothers Karamazov",
60: "The Catcher in the Rye",
61: "Lord of the Flies",
62: "The Hobbit",
63: "The Lord of the Rings",
64: "Harry Potter and the Philosopher’s Stone",
65: "The Kite Runner",
66: "A Thousand Splendid Suns",
67: "The Book Thief",
68: "The Fault in Our Stars",
69: "Grit: The Power of Passion and Perseverance",
70: "The Power of Now",
71: "Start with Why",
72: "Zero to One",
73: "The Lean Startup",
74: "Hooked",
75: "Clean Code",
76: "The Pragmatic Programmer",
77: "Introduction to Algorithms",
78: "Structure and Interpretation of Computer Programs",
79: "Artificial Intelligence: A Modern Approach",
80: "The Code Book",
81: "Gödel, Escher, Bach",
82: "The Innovators",
83: "Steve Jobs",
84: "Elon Musk",
85: "Shoe Dog",
86: "Thinking in Systems",
87: "Factfulness",
88: "Range",
89: "Drive",
90: "Quiet",
91: "The Design of Everyday Things",
92: "Don’t Make Me Think",
93: "The Psychology of Money",
94: "Your Money or Your Life",
95: "I Will Teach You to Be Rich",
96: "The Four-Hour Workweek",
97: "Tools of Titans",
98: "The Hard Thing About Hard Things",
99: "Good to Great",
100: "Built to Last"
}
l2={}
l3=[]